name = "cf-workers-status-page"
workers_dev = true
account_id = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2025-12-31"

[triggers]
crons = ["*/2 * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
# [env.production]
kv_namespaces = [{binding="KV_STATUS_PAGE", id="9ba8bdd57e7a408e9f1e30eb2982320f"}]
# zone_id="xxx"
# route="xxx"
